import { Workshop } from "@/app/api/add-workshop/route";

export const dummyWorkshops: Workshop[] = [
   {
      workshopName: "Alpha Auto Solutions",
      ownerName: "John Doe",
      address: "12 Adeola Odeku Street",
      state: "Lagos",
      city: "Ikeja",
      phone: "08123456789",
      email: "alphaautosolutions@example.com",
      website: "http://alphaautosolutions.com",
      specializations: ["General Repair", "Electrical"],
      description: "Providing top-notch auto repair services in Ikeja.",
      termsAccepted: true,
   },
   {
      workshopName: "Beta Auto Repair",
      ownerName: "Jane Smith",
      address: "22 Independence Avenue",
      state: "Abuja",
      city: "Garki",
      phone: "08098765432",
      email: "betaautorepair@example.com",
      website: "http://betaautorepair.com",
      specializations: ["Engine", "Transmission"],
      description: "Specialists in engine and transmission repairs in Abuja.",
      termsAccepted: true,
   },
   {
      workshopName: "Delta Auto Works",
      ownerName: "Mike Johnson",
      address: "5 Herbert Macaulay Road",
      state: "Rivers",
      city: "Port Harcourt",
      phone: "07011223344",
      email: "deltaautoworks@example.com",
      website: "http://deltaautoworks.com",
      specializations: ["Brakes", "Suspension"],
      description: "Expert brake and suspension services in Port Harcourt.",
      termsAccepted: true,
   },
   {
      workshopName: "Epsilon Motors",
      ownerName: "Nkechi Obi",
      address: "15 Uyo Road",
      state: "Akwa Ibom",
      city: "Uyo",
      phone: "08044332211",
      email: "epsilonmotors@example.com",
      website: "http://epsilonmotors.com",
      specializations: ["General Repair", "Engine"],
      description: "Reliable auto repair services in Uyo.",
      termsAccepted: true,
   },
   {
      workshopName: "Gamma Vehicle Care",
      ownerName: "Bello Musa",
      address: "10 Zaria Road",
      state: "Kano",
      city: "Kano",
      phone: "07098765432",
      email: "gammavehiclecare@example.com",
      website: "http://gammavehiclecare.com",
      specializations: ["Transmission", "Electrical"],
      description: "Your trusted partner for electrical repairs in Kano.",
      termsAccepted: true,
   },
   {
      workshopName: "Sigma Auto Experts",
      ownerName: "Aisha Usman",
      address: "18 Kaduna Crescent",
      state: "Kaduna",
      city: "Kaduna",
      phone: "09011234567",
      email: "sigmaautoexperts@example.com",
      website: "http://sigmaautoexperts.com",
      specializations: ["Suspension", "Engine"],
      description: "Professional auto experts based in Kaduna.",
      termsAccepted: true,
   },
   {
      workshopName: "Omega Mechanics Hub",
      ownerName: "Chinedu Eze",
      address: "25 Awolowo Way",
      state: "Oyo",
      city: "Ibadan",
      phone: "08122334455",
      email: "omegamechanics@example.com",
      website: "http://omegamechanics.com",
      specializations: ["Brakes", "General Repair"],
      description:
         "Your go-to mechanics for reliable repair services in Ibadan.",
      termsAccepted: true,
   },
   {
      workshopName: "Elite Auto Clinic",
      ownerName: "Funmi Adeola",
      address: "3 Tinubu Street",
      state: "Lagos",
      city: "Surulere",
      phone: "08033445566",
      email: "eliteautoclinic@example.com",
      website: "http://eliteautoclinic.com",
      specializations: ["Transmission", "Electrical"],
      description: "Specialized services for auto repair in Surulere.",
      termsAccepted: true,
   },
   {
      workshopName: "Profix Repairs",
      ownerName: "Ahmed Garba",
      address: "14 Sabon Gari Road",
      state: "Kano",
      city: "Kano",
      phone: "08155667788",
      email: "profixrepairs@example.com",
      website: "http://profixrepairs.com",
      specializations: ["General Repair", "Brakes"],
      description: "Affordable and efficient auto services in Kano.",
      termsAccepted: true,
   },
   {
      workshopName: "Supreme AutoFix",
      ownerName: "Tolu Omotayo",
      address: "20 Obafemi Awolowo Avenue",
      state: "Ogun",
      city: "Abeokuta",
      phone: "08099887766",
      email: "supremeautofix@example.com",
      website: "http://supremeautofix.com",
      specializations: ["Engine", "Suspension"],
      description: "Supreme services for all your vehicle needs in Abeokuta.",
      termsAccepted: true,
   },
   {
      workshopName: "Victory Motors",
      ownerName: "Segun Ajayi",
      address: "7 Festac Road",
      state: "Lagos",
      city: "Festac",
      phone: "08033221100",
      email: "victorymotors@example.com",
      website: "http://victorymotors.com",
      specializations: ["Electrical", "Transmission"],
      description:
         "Experienced mechanics ensuring quality repair services in Festac.",
      termsAccepted: true,
   },
   {
      workshopName: "Top Gear Auto",
      ownerName: "Abubakar Sadiq",
      address: "11 Unity Street",
      state: "Niger",
      city: "Minna",
      phone: "08044455566",
      email: "topgearauto@example.com",
      website: "http://topgearauto.com",
      specializations: ["Brakes", "Engine"],
      description:
         "Leading repair services in Minna with a focus on precision.",
      termsAccepted: true,
   },
   {
      workshopName: "Reliable Motors",
      ownerName: "Grace Okafor",
      address: "19 Anambra Avenue",
      state: "Anambra",
      city: "Awka",
      phone: "08100998877",
      email: "reliablemotors@example.com",
      website: "http://reliablemotors.com",
      specializations: ["Suspension", "Transmission"],
      description: "Providing trusted repair solutions in Awka.",
      termsAccepted: true,
   },
   {
      workshopName: "Precision Auto Clinic",
      ownerName: "Emeka Ibe",
      address: "9 Ogundele Road",
      state: "Ogun",
      city: "Ijebu Ode",
      phone: "07067778899",
      email: "precisionautoclinic@example.com",
      website: "http://precisionautoclinic.com",
      specializations: ["Engine", "Suspension"],
      description: "Precision engine and suspension repairs in Ijebu Ode.",
      termsAccepted: true,
   },
   {
      workshopName: "Silver Star Garage",
      ownerName: "Chijioke Uzo",
      address: "32 Ogui Road",
      state: "Enugu",
      city: "Enugu",
      phone: "09011223344",
      email: "silverstargarage@example.com",
      website: "http://silverstargarage.com",
      specializations: ["Brakes", "Electrical"],
      description: "Expert brake and electrical repairs in Enugu.",
      termsAccepted: true,
   },
   {
      workshopName: "Kingdom Auto Service",
      ownerName: "Ruth Akintoye",
      address: "13 Murtala Mohammed Way",
      state: "Kwara",
      city: "Ilorin",
      phone: "08123457689",
      email: "kingdomautoservice@example.com",
      website: "http://kingdomautoservice.com",
      specializations: ["Transmission", "General Repair"],
      description: "Trusted auto services in Ilorin.",
      termsAccepted: true,
   },
   {
      workshopName: "Smart Mechanics Hub",
      ownerName: "Sani Ibrahim",
      address: "16 Garki Road",
      state: "Yobe",
      city: "Damaturu",
      phone: "07012345678",
      email: "smartmechanicshub@example.com",
      website: "http://smartmechanicshub.com",
      specializations: ["Suspension", "Engine"],
      description: "Specialists in suspension and engine repair services.",
      termsAccepted: true,
   },
   {
      workshopName: "Total Auto Experts",
      ownerName: "Idris Abubakar",
      address: "23 Lagos Crescent",
      state: "Benue",
      city: "Makurdi",
      phone: "08099887766",
      email: "totalautoexperts@example.com",
      website: "http://totalautoexperts.com",
      specializations: ["Brakes", "Transmission"],
      description: "Comprehensive auto repair services in Makurdi.",
      termsAccepted: true,
   },
   {
      workshopName: "QuickFix Auto Care",
      ownerName: "Sola Bamidele",
      address: "8 Oke-Ado Road",
      state: "Ekiti",
      city: "Ado Ekiti",
      phone: "08144556677",
      email: "quickfixautocare@example.com",
      website: "http://quickfixautocare.com",
      specializations: ["Electrical", "General Repair", "Brakes"],
      description: "Quick and affordable auto services in Ado Ekiti.",
      termsAccepted: true,
   },
];
